-- Gerado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   em:        2025-06-03 23:25:19 BRT
--   site:      Oracle Database 11g
--   tipo:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

DROP TABLE BI_DIM_CATEGORIA;
CREATE TABLE BI_DIM_CATEGORIA 
    ( 
     COD_CATEGORIA      NUMBER  NOT NULL , 
     DSC_NOME_CATEGORIA VARCHAR2 (30)  NOT NULL 
    ) 
;

COMMENT ON COLUMN BI_DIM_CATEGORIA.COD_CATEGORIA IS 'Código de categorias.' 
;

COMMENT ON COLUMN BI_DIM_CATEGORIA.DSC_NOME_CATEGORIA IS 'Nome da categoria.' 
;

ALTER TABLE BI_DIM_CATEGORIA 
    ADD CONSTRAINT BI_DIM_CATEGORIA_PK PRIMARY KEY ( COD_CATEGORIA ) ;

CREATE TABLE BI_DIM_CIDADE 
    ( 
     COD_CIDADE      NUMBER  NOT NULL , 
     DSC_NOME_CIDADE VARCHAR2 (20)  NOT NULL , 
     COD_POSTAL      NUMBER , 
     COD_PAIS        NUMBER  NOT NULL 
    ) 
;

COMMENT ON COLUMN BI_DIM_CIDADE.COD_CIDADE IS 'Código da cidade.' 
;

COMMENT ON COLUMN BI_DIM_CIDADE.DSC_NOME_CIDADE IS 'Nome da cidade.' 
;

COMMENT ON COLUMN BI_DIM_CIDADE.COD_POSTAL IS 'Código postal - CEP.' 
;

COMMENT ON COLUMN BI_DIM_CIDADE.COD_PAIS IS 'Código do País.' 
;

ALTER TABLE BI_DIM_CIDADE 
    ADD CONSTRAINT BI_DIM_CIDADE_PK PRIMARY KEY ( COD_CIDADE ) ;

CREATE TABLE BI_DIM_CLIENTE 
    ( 
     COD_CLIENTE           NUMBER  NOT NULL , 
     DSC_PRIMEIRO_NOME     VARCHAR2 (15)  NOT NULL , 
     DSC_INICIAL_SOBRENOME CHAR (1) , 
     DSC_ULTIMO_NOME       VARCHAR2 (20)  NOT NULL , 
     COD_CIDADE            NUMBER  NOT NULL , 
     DSC_ENDERECO          VARCHAR2 (100)  NOT NULL 
    ) 
;

COMMENT ON COLUMN BI_DIM_CLIENTE.COD_CLIENTE IS 'Código do cliente.' 
;

COMMENT ON COLUMN BI_DIM_CLIENTE.DSC_PRIMEIRO_NOME IS 'Primeiro nome do cliente.' 
;

COMMENT ON COLUMN BI_DIM_CLIENTE.DSC_INICIAL_SOBRENOME IS 'Abreviação do nome do meio.' 
;

COMMENT ON COLUMN BI_DIM_CLIENTE.DSC_ULTIMO_NOME IS 'Último nome.' 
;

COMMENT ON COLUMN BI_DIM_CLIENTE.COD_CIDADE IS 'Código da cidade.' 
;

COMMENT ON COLUMN BI_DIM_CLIENTE.DSC_ENDERECO IS 'Endereço do cliente.' 
;

ALTER TABLE BI_DIM_CLIENTE 
    ADD CONSTRAINT BI_DIM_CLIENTE_PK PRIMARY KEY ( COD_CLIENTE ) ;

CREATE TABLE BI_DIM_COLABORADOR 
    ( 
     COD_COLABORADOR       NUMBER  NOT NULL , 
     DSC_PRIMEIRO_NOME     VARCHAR2 (20)  NOT NULL , 
     DSC_INICIAL_SOBRENOME CHAR (1) , 
     DSC_ULTIMO_NOME       VARCHAR2 (30)  NOT NULL , 
     DAT_ANIVERSARIO       DATE , 
     DSC_GENERO            CHAR (1)  NOT NULL , 
     COD_CIDADE            NUMBER  NOT NULL , 
     DAT_CONTRATACAO       DATE  NOT NULL 
    ) 
;

COMMENT ON COLUMN BI_DIM_COLABORADOR.COD_COLABORADOR IS 'Código do colaborador.' 
;

COMMENT ON COLUMN BI_DIM_COLABORADOR.DSC_PRIMEIRO_NOME IS 'Nome do colaborador.' 
;

COMMENT ON COLUMN BI_DIM_COLABORADOR.DSC_INICIAL_SOBRENOME IS 'Abreviação do nome do meio.' 
;

COMMENT ON COLUMN BI_DIM_COLABORADOR.DSC_ULTIMO_NOME IS 'Último nome.' 
;

COMMENT ON COLUMN BI_DIM_COLABORADOR.DAT_ANIVERSARIO IS 'Data de aniversário do colaborador.' 
;

COMMENT ON COLUMN BI_DIM_COLABORADOR.DSC_GENERO IS 'Gênero do colaborador.' 
;

COMMENT ON COLUMN BI_DIM_COLABORADOR.COD_CIDADE IS 'CÓDIGO DA CIDADE.' 
;

COMMENT ON COLUMN BI_DIM_COLABORADOR.DAT_CONTRATACAO IS 'DATA DE CONTRAÇÃO DO COLABORADOR.' 
;

ALTER TABLE BI_DIM_COLABORADOR 
    ADD CONSTRAINT BI_DIM_COLABORADOR_PK PRIMARY KEY ( COD_COLABORADOR ) ;

CREATE TABLE BI_DIM_PAIS 
    ( 
     COD_PAIS      NUMBER  NOT NULL , 
     DSC_NOME_PAIS VARCHAR2 (30)  NOT NULL , 
     SGL_PAIS      CHAR (2)  NOT NULL 
    ) 
;

COMMENT ON COLUMN BI_DIM_PAIS.COD_PAIS IS 'Código do País.' 
;

COMMENT ON COLUMN BI_DIM_PAIS.DSC_NOME_PAIS IS 'Nome do País.' 
;

COMMENT ON COLUMN BI_DIM_PAIS.SGL_PAIS IS 'Sigla do País.' 
;

ALTER TABLE BI_DIM_PAIS 
    ADD CONSTRAINT BI_DIM_PAIS_PK PRIMARY KEY ( COD_PAIS ) ;

CREATE TABLE BI_DIM_PRODUTO 
    ( 
     COD_PRODUTO       NUMBER  NOT NULL , 
     DSC_NOME_PRODUTO  VARCHAR2 (20)  NOT NULL , 
     VAL_PRECO         NUMBER  NOT NULL , 
     COD_CATEGORIA     NUMBER  NOT NULL , 
     DSC_CLASSE        VARCHAR2 (10)  NOT NULL , 
     DAT_MODIFICACAO   DATE  NOT NULL , 
     DSC_RESISTENCIA   VARCHAR2 (10)  NOT NULL , 
     DSC_ALERGENICO    VARCHAR2 (10)  NOT NULL , 
     QTD_DIAS_VALIDADE NUMBER 
    ) 
;

COMMENT ON COLUMN BI_DIM_PRODUTO.COD_PRODUTO IS 'CÓDIGO DO PRODUTO.' 
;

COMMENT ON COLUMN BI_DIM_PRODUTO.DSC_NOME_PRODUTO IS 'NOME DO PRODUTO.' 
;

COMMENT ON COLUMN BI_DIM_PRODUTO.VAL_PRECO IS 'PREÇO.' 
;

COMMENT ON COLUMN BI_DIM_PRODUTO.COD_CATEGORIA IS 'CÓDIGO DA CATEGORIA.
' 
;

COMMENT ON COLUMN BI_DIM_PRODUTO.DSC_CLASSE IS 'CLASSE ECONÔMICA.' 
;

COMMENT ON COLUMN BI_DIM_PRODUTO.DAT_MODIFICACAO IS 'DATA DA MODIFICAÇÃO.' 
;

COMMENT ON COLUMN BI_DIM_PRODUTO.DSC_RESISTENCIA IS 'RESISTÊNCIA DO PRODUTO/DURABILIDADE.' 
;

COMMENT ON COLUMN BI_DIM_PRODUTO.DSC_ALERGENICO IS 'DESCRIÇÃO SE É UM PRODUTO ALERGÊNICO.' 
;

COMMENT ON COLUMN BI_DIM_PRODUTO.QTD_DIAS_VALIDADE IS 'DIAS DE VALIDADE.' 
;

ALTER TABLE BI_DIM_PRODUTO 
    ADD CONSTRAINT BI_DIM_PRODUTO_PK PRIMARY KEY ( COD_PRODUTO ) ;

CREATE TABLE BI_FATO_VENDA 
    ( 
     COD_VENDA       NUMBER  NOT NULL , 
     COD_VENDEDOR    NUMBER  NOT NULL , 
     COD_CLIENTE     NUMBER  NOT NULL , 
     COD_PRODUTO     NUMBER  NOT NULL , 
     NUM_QUANTIDADE  NUMBER  NOT NULL , 
     VAL_DESCONTO    NUMBER  NOT NULL , 
     VAL_PRECO_TOTAL NUMBER  NOT NULL , 
     DAT_VENDA       DATE  NOT NULL , 
     COD_TRANSACAO   VARCHAR2 (30)  NOT NULL 
    ) 
;

COMMENT ON COLUMN BI_FATO_VENDA.COD_VENDA IS 'Código da venda.' 
;

COMMENT ON COLUMN BI_FATO_VENDA.COD_VENDEDOR IS 'Código do vendedor.' 
;

COMMENT ON COLUMN BI_FATO_VENDA.COD_CLIENTE IS 'Código do cliente.' 
;

COMMENT ON COLUMN BI_FATO_VENDA.COD_PRODUTO IS 'Código do produto.' 
;

COMMENT ON COLUMN BI_FATO_VENDA.NUM_QUANTIDADE IS 'Quantidade.' 
;

COMMENT ON COLUMN BI_FATO_VENDA.VAL_DESCONTO IS 'Desconto no preço.' 
;

COMMENT ON COLUMN BI_FATO_VENDA.VAL_PRECO_TOTAL IS 'Preço total da venda.' 
;

COMMENT ON COLUMN BI_FATO_VENDA.DAT_VENDA IS 'Data de lançamento da venda.' 
;

COMMENT ON COLUMN BI_FATO_VENDA.COD_TRANSACAO IS 'Número da transação de venda.' 
;

ALTER TABLE BI_FATO_VENDA 
    ADD CONSTRAINT BI_FATO_VENDA_PK PRIMARY KEY ( COD_VENDA ) ;



-- Relatório do Resumo do Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                              7
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
